//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiftlikCalisma
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ships
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ships()
        {
            this.Childs = new HashSet<Childs>();
            this.ShipVaccine = new HashSet<ShipVaccine>();
        }
    
        public int ShipId { get; set; }
        public int CiftlikId { get; set; }
        public int DevletId { get; set; }
        public Nullable<double> Price { get; set; }
        public string durum { get; set; }
        public string Not { get; set; }
        public string cinsiyet { get; set; }
        public System.DateTime DogumTarihi { get; set; }
        public string DogumTipi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Childs> Childs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShipVaccine> ShipVaccine { get; set; }
    }
}
