//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiftlikCalisma
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipVaccine
    {
        public int VaccineID { get; set; }
        public string VaccineName { get; set; }
        public System.DateTime VaccineDate { get; set; }
        public double Price { get; set; }
        public int ShipId { get; set; }
    
        public virtual Ships Ships { get; set; }
    }
}
